module.exports = [
    {
        name: "Vansh Chopra",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Ram Chopra",
        cgpa:7.89,
        rollno: 20105078,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "CSE",
        semester:4,
        club:"acm-css".toUpperCase(),
    }, {
        name: "Muskaan Chopra",
        cgpa:7.89,
        rollno: 20105079,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    }, {
        name: "Vaibhav Chopra",
        cgpa:7.89,
        rollno: 20105075,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "Civil",
        semester:4,
        club:"acm-css".toUpperCase(),
    }, {
        name: "Jatin Chopra",
        cgpa:7.89,
        rollno: 20105070,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "Metta",
        semester:4,
        club:"acm-css".toUpperCase(),
    }, {
        name: "Anjali Chopra",
        cgpa:7.89,
        rollno: 20105080,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "CSE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Om Chopra",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to boys",
        branch: "EE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Sumanaya Chopra",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Rahul Khanna",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Brijesh kapoor",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Vipin Bansal",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Karun Kapoor",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Ishika Sharma",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Abhishek Verma",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Kriti Mahajan",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Gourav Mucchal",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Aman Gupta",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Gurjot Singh",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Nikita Sharma",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },
    {
        name: "Ram lal",
        cgpa:7.89,
        rollno: 20105077,
        state: "Punjab",
        description: "Alwasys Talks to girls",
        branch: "ECE",
        semester:4,
        club:"acm-css".toUpperCase(),
    },

];